// Base de données massive de défis (environ 10 000 défis)

const gamesData = {
    truthOrDare: {
        name: "Action ou Vérité",
        truths: [
            // Questions embarrassantes
            "Raconte ton pire date",
            "Quelle est ta plus grosse honte ?",
            "As-tu déjà menti à quelqu'un dans cette pièce ?",
            "Quelle est la chose la plus embarrassante sur ton téléphone ?",
            "Qui dans cette pièce aimerais-tu embrasser ?",
            "Quel est ton plus grand secret ?",
            "As-tu déjà triché dans une relation ?",
            "Quelle est ta plus grosse peur ?",
            "Raconte un mensonge que tu as dit récemment",
            "Qui est la dernière personne que tu as stalké sur les réseaux sociaux ?",
            "Quelle est la chose la plus bizarre que tu as faite bourré(e) ?",
            "As-tu déjà volé quelque chose ?",
            "Quel est ton fantasme le plus fou ?",
            "Si tu pouvais sortir avec quelqu'un ici, qui ce serait ?",
            "Quelle est la chose la plus gênante que tes parents t'aient surpris en train de faire ?",

            // Relations et amour
            "As-tu déjà eu le béguin pour un prof ?",
            "Combien de personnes as-tu embrassées ?",
            "Quel est le pire surnom qu'on t'ait donné ?",
            "As-tu déjà envoyé un message à la mauvaise personne ?",
            "Quelle est ta pire rupture ?",
            "As-tu déjà eu des sentiments pour l'ex de quelqu'un ?",
            "Raconte ton premier baiser",
            "As-tu déjà été rejeté(e) publiquement ?",
            "Quelle est la chose la plus gênante que tu aies faite pour impressionner quelqu'un ?",
            "As-tu déjà espionné ton crush sur les réseaux ?",
            "Quel est ton type idéal vraiment ?",
            "As-tu déjà menti sur ton âge ?",
            "Quelle est la personne la plus âgée/jeune que tu aies fréquentée ?",
            "As-tu déjà ghosté quelqu'un ?",
            "Raconte ton coup de foudre le plus ridicule",

            // Secrets et mensonges
            "Quel secret gardes-tu à tes parents ?",
            "As-tu déjà menti sur ton CV ?",
            "Quelle est la chose la plus illégale que tu aies faite ?",
            "As-tu déjà triché à un examen ?",
            "Quel est ton plaisir coupable ?",
            "As-tu déjà fait semblant d'être malade ?",
            "Quelle est ta plus grosse dépense secrète ?",
            "As-tu déjà volé quelque chose dans un magasin ?",
            "Quel est le mensonge que tu dis le plus souvent ?",
            "As-tu déjà lu le journal intime de quelqu'un ?",
            "Quelle est la chose que tu fais en cachette ?",
            "As-tu déjà menti sur tes sentiments ?",
            "Quel secret connais-tu sur quelqu'un ici ?",
            "As-tu déjà fouillé dans le téléphone de quelqu'un ?",
            "Quelle est ta double vie secrète ?",

            // Expériences gênantes
            "Raconte ta pire cuite",
            "Quelle est ta plus grosse gaffe en public ?",
            "As-tu déjà vomi en soirée ?",
            "Raconte ton moment le plus embarrassant à l'école",
            "As-tu déjà été surpris(e) en train de te parler à toi-même ?",
            "Quelle est la chose la plus gênante que tu aies dit à haute voix ?",
            "As-tu déjà envoyé un snap embarrassant par erreur ?",
            "Raconte une fois où tu t'es ridiculisé(e) devant ton crush",
            "As-tu déjà fait un truc bizarre en dormant ?",
            "Quelle est ta pire photo sur Internet ?",
            "As-tu déjà pété bruyamment en public ?",
            "Raconte ton fail le plus épique",
            "As-tu déjà appelé ton prof 'maman' ou 'papa' ?",
            "Quelle est ta gaffe la plus mémorable ?",
            "As-tu déjà oublié le nom de quelqu'un pendant une conversation ?",

            // Réseaux sociaux et technologie
            "Montre ton historique de recherche",
            "Quel est ton mot de passe le plus embarrassant ?",
            "Combien de fois regardes-tu ton ex sur les réseaux ?",
            "As-tu déjà créé un faux profil ?",
            "Quelle est la chose la plus bizarre de ton historique YouTube ?",
            "Combien de selfies prends-tu avant de poster ?",
            "As-tu déjà supprimé un post par manque de likes ?",
            "Quel est ton DM le plus gênant ?",
            "As-tu déjà acheté des followers ?",
            "Quelle est l'appli que tu utilises le plus en secret ?",
            "Combien de temps passes-tu sur TikTok par jour ?",
            "As-tu déjà bloqué quelqu'un sans raison ?",
            "Quel est le message le plus pathétique que tu aies envoyé ?",
            "As-tu déjà pleuré à cause d'un commentaire en ligne ?",
            "Quelle est ta recherche Google la plus étrange ?",

            // Famille
            "Quel membre de ta famille t'énerve le plus ?",
            "As-tu un préféré entre tes parents ?",
            "Raconte un secret de famille embarrassant",
            "Quelle règle de tes parents tu ne respectes jamais ?",
            "As-tu déjà menti à tes parents aujourd'hui ?",
            "Quel est le surnom gênant que te donne ta famille ?",
            "Raconte une dispute familiale ridicule",
            "As-tu déjà fait pleurer un membre de ta famille ?",
            "Quelle est la chose que ta famille ne sait pas sur toi ?",
            "As-tu déjà volé de l'argent à tes parents ?",
            "Quel est ton plus gros mensonge à ta famille ?",
            "Raconte une fois où tu as embarrassé tes parents",
            "As-tu un secret avec un membre de ta famille ?",
            "Quelle tradition familiale détestes-tu ?",
            "As-tu déjà cassé quelque chose et accusé quelqu'un d'autre ?",

            // Amitié
            "As-tu déjà parlé dans le dos d'un ami ?",
            "Quel ami t'énerve secrètement ?",
            "As-tu déjà été jaloux(se) d'un ami ?",
            "Raconte une fois où tu as trahi la confiance d'un ami",
            "Quel ami ne supportes-tu plus vraiment ?",
            "As-tu déjà menti pour éviter de voir un ami ?",
            "Quel secret d'ami as-tu révélé ?",
            "As-tu déjà eu le béguin sur le copain/copine d'un ami ?",
            "Raconte une dispute d'amis ridicule",
            "As-tu déjà volé l'idée de quelqu'un ?",
            "Quel ami regrettes-tu d'avoir perdu ?",
            "As-tu déjà ghosté un ami ?",
            "Raconte un mensonge que tu as dit à un ami",
            "As-tu des amis que tu n'aimes pas vraiment ?",
            "Quelle est la chose la plus méchante qu'un ami t'ait faite ?",

            // École/Travail
            "As-tu déjà séché les cours ?",
            "Quelle est ta pire note ?",
            "As-tu déjà copié sur quelqu'un ?",
            "Raconte ta pire journée au travail/à l'école",
            "As-tu déjà fait porter le chapeau à quelqu'un ?",
            "Quel prof/collègue détestes-tu ?",
            "As-tu déjà été collé(e) ?",
            "Raconte une fois où tu t'es endormi en cours/réunion",
            "As-tu déjà fait semblant de travailler ?",
            "Quelle est ta pire excuse pour un retard ?",
            "As-tu déjà menti sur tes compétences ?",
            "Raconte ton échec le plus honteux",
            "As-tu déjà pleuré à l'école/au travail ?",
            "Quel est ton pire souvenir scolaire ?",
            "As-tu déjà été viré ou renvoyé ?",

            // Habitudes bizarres
            "Quelle est ton habitude la plus dégoûtante ?",
            "As-tu des rituels bizarres ?",
            "Parles-tu seul(e) ?",
            "As-tu des phobies étranges ?",
            "Quelle est ta manie la plus bizarre ?",
            "As-tu des superstitions ridicules ?",
            "Quelle est ta collection secrète ?",
            "As-tu un talent caché embarrassant ?",
            "Quelle est la chose bizarre que tu fais au lit ?",
            "As-tu des TOC ?",
            "Quelle est ton obsession secrète ?",
            "As-tu déjà mangé quelque chose de bizarre ?",
            "Quelle est ta routine matinale la plus gênante ?",
            "As-tu des habitudes d'enfance que tu gardes ?",
            "Quelle est la chose la plus bizarre que tu collectionnes ?",

            // Corps et apparence
            "Quelle partie de ton corps détestes-tu ?",
            "As-tu déjà fait de la chirurgie esthétique ?",
            "Combien de temps passes-tu devant le miroir ?",
            "As-tu déjà menti sur ton poids ?",
            "Quelle est ta plus grosse insécurité physique ?",
            "As-tu des poils embarrassants ?",
            "Raconte ton pire look",
            "As-tu déjà eu des problèmes de peau embarrassants ?",
            "Quelle est ta pire coupe de cheveux ?",
            "As-tu déjà raté un tatouage/piercing ?",
            "Combien de temps mets-tu pour te préparer ?",
            "As-tu déjà menti sur ta taille ?",
            "Quelle est ta pire photo d'identité ?",
            "As-tu déjà eu un accident vestimentaire en public ?",
            "Quelle est la chose que tu changerais sur ton corps ?",

            // Argent
            "Combien as-tu sur ton compte en banque ?",
            "Quelle est ta plus grosse dépense stupide ?",
            "As-tu des dettes cachées ?",
            "Combien gagnes-tu vraiment ?",
            "As-tu déjà emprunté de l'argent sans le rendre ?",
            "Quelle est la chose la plus chère que tu aies cassée ?",
            "As-tu déjà menti sur ton salaire ?",
            "Combien dépenses-tu en futilités par mois ?",
            "As-tu de l'argent caché ?",
            "Quelle est ta pire décision financière ?",
            "As-tu déjà arnaqué quelqu'un ?",
            "Combien as-tu de cartes de crédit ?",
            "Quelle est ta dette maximale atteinte ?",
            "As-tu déjà volé de l'argent ?",
            "Combien coûte ton addiction la plus chère ?",

            // Peurs et phobies
            "Quelle est ta plus grande peur irrationnelle ?",
            "De quoi as-tu le plus honte ?",
            "Quelle est ta peur d'enfance qui persiste ?",
            "As-tu peur du noir ?",
            "Quelle situation te panique le plus ?",
            "As-tu des cauchemars récurrents ?",
            "De quel animal as-tu le plus peur ?",
            "Quelle est ta peur en société ?",
            "As-tu peur de la mort ?",
            "Quelle est la chose qui te stresse le plus ?",
            "As-tu des angoisses nocturnes ?",
            "De quoi as-tu le plus peur pour ton avenir ?",
            "Quelle situation t'angoisse le plus ?",
            "As-tu des crises de panique ?",
            "Quelle est ta phobie la plus bizarre ?",

            // Rêves et ambitions
            "Quel est ton rêve le plus fou ?",
            "Quelle ambition as-tu abandonnée ?",
            "Si tu pouvais être quelqu'un d'autre, qui ?",
            "Quel est ton plus grand regret ?",
            "Qu'aurais-tu aimé faire de ta vie ?",
            "Quel rêve d'enfant as-tu perdu ?",
            "Si tu pouvais recommencer, que changerais-tu ?",
            "Quelle est ton ambition secrète ?",
            "Quel métier rêvais-tu de faire enfant ?",
            "Si tu gagnais au loto, que ferais-tu ?",
            "Quel est ton fantasme de vie ?",
            "Où te vois-tu dans 10 ans ?",
            "Quelle est la chose que tu veux accomplir avant de mourir ?",
            "Quel est ton rêve le plus inavouable ?",
            "Si tu pouvais avoir un super-pouvoir, lequel ?",

            // Préférences étranges
            "Quel est ton kink le plus bizarre ?",
            "Quelle célébrité trouves-tu sexy bizarrement ?",
            "Quel cartoon trouvais-tu attirant enfant ?",
            "Quelle est ta préférence la plus embarrassante ?",
            "Quel type de personne t'attire secrètement ?",
            "Quelle est ton obsession sexuelle ?",
            "As-tu des fétiches bizarres ?",
            "Quelle est ta position préférée ?",
            "Combien de partenaires as-tu eu ?",
            "Quel est ton fantasme secret ?",
            "As-tu déjà regardé du contenu adulte bizarre ?",
            "Quelle est ta zone érogène la plus inattendue ?",
            "As-tu des pratiques sexuelles inhabituelles ?",
            "Quel est ton turn-on le plus étrange ?",
            "Raconte ton expérience la plus bizarre au lit",

            // Personnalité cachée
            "Quelle est ta part la plus sombre ?",
            "As-tu déjà voulu te venger de quelqu'un ?",
            "Quelle est la chose la plus méchante que tu aies pensée ?",
            "As-tu des pensées intrusives ?",
            "Quelle est ton opinion la plus impopulaire ?",
            "Juges-tu secrètement les gens ?",
            "As-tu déjà souhaité du mal à quelqu'un ?",
            "Quelle est ta pensée la plus horrible ?",
            "Es-tu vraiment une bonne personne ?",
            "As-tu déjà manipulé quelqu'un ?",
            "Quelle est ta plus grande hypocrisie ?",
            "As-tu des préjugés dont tu as honte ?",
            "Quelle est la chose que tu juges le plus chez les autres ?",
            "As-tu déjà profité de quelqu'un ?",
            "Quelle est ta plus grande faiblesse morale ?",

            // Addictions et vices
            "Quelle est ton addiction secrète ?",
            "Combien de cigarettes/joints fumes-tu vraiment ?",
            "As-tu déjà pris des drogues dures ?",
            "Quelle est ta dépendance la plus embarrassante ?",
            "Combien d'alcool bois-tu par semaine ?",
            "As-tu des addictions comportementales ?",
            "Quelle substance as-tu essayée ?",
            "As-tu déjà eu un problème avec l'alcool ?",
            "Quelle est ton vice caché ?",
            "As-tu des comportements compulsifs ?",
            "Quelle mauvaise habitude ne peux-tu pas arrêter ?",
            "As-tu déjà menti sur ta consommation ?",
            "Quelle est la drogue la plus folle que tu aies essayée ?",
            "As-tu des dépendances numériques ?",
            "Quel est ton péché mignon inavouable ?",

            // Passé honteux
            "Quelle est la chose de ton passé que tu voudrais effacer ?",
            "Raconte ton adolescence la plus cringe",
            "Quel souvenir te fait encore rougir ?",
            "As-tu fait des choses dont tu as honte ?",
            "Quelle phase embarrassante as-tu traversée ?",
            "Raconte ton pire look d'ado",
            "Quelle musique écoutais-tu que tu caches maintenant ?",
            "As-tu eu des passions gênantes ?",
            "Quelle est ta période la plus dark ?",
            "Raconte une bêtise d'enfance terrible",
            "As-tu fait des trucs illégaux ado ?",
            "Quel est ton souvenir le plus honteux ?",
            "Raconte ta pire phase emo/gothique",
            "As-tu des regrets profonds ?",
            "Quelle erreur de jeunesse regrettes-tu le plus ?",

            // Hygiène
            "Combien de fois te laves-tu vraiment par semaine ?",
            "As-tu déjà porté le même sous-vêtement plusieurs jours ?",
            "Combien de fois changes-tu tes draps ?",
            "Te laves-tu les mains après les toilettes ?",
            "As-tu déjà sauté la douche plusieurs jours de suite ?",
            "Quelle est ton habitude la plus dégoûtante ?",
            "Te brosses-tu les dents 2 fois par jour vraiment ?",
            "As-tu déjà réutilisé des vêtements sales ?",
            "Quelle est la partie de ton corps que tu négliges ?",
            "Combien de temps gardes-tu ta serviette ?",
            "As-tu des habitudes d'hygiène douteuses ?",
            "Te laves-tu les pieds sous la douche ?",
            "As-tu déjà senti mauvais sciemment ?",
            "Quelle est ta routine d'hygiène vraiment ?",
            "As-tu déjà menti sur quand tu t'es lavé ?",

            // Nourriture
            "Quelle est la chose la plus dégoûtante que tu aies mangée ?",
            "As-tu déjà mangé de la bouffe périmée volontairement ?",
            "Quel est ton comportement alimentaire le plus bizarre ?",
            "Manges-tu au lit ?",
            "As-tu déjà volé de la nourriture ?",
            "Quelle est ta combinaison alimentaire la plus étrange ?",
            "Manges-tu des choses tombées par terre ?",
            "As-tu des troubles alimentaires ?",
            "Quelle est ta pire frénésie alimentaire ?",
            "Manges-tu en cachette ?",
            "As-tu déjà menti sur ce que tu manges ?",
            "Quel aliment manges-tu de façon bizarre ?",
            "As-tu des addictions alimentaires ?",
            "Combien de fast-food manges-tu par semaine ?",
            "Quelle est ta honte alimentaire ?",

            // Mensonges courants
            "Sur quoi mens-tu régulièrement ?",
            "As-tu menti aujourd'hui ?",
            "Quel mensonge dis-tu pour éviter les gens ?",
            "Mens-tu sur ton âge ?",
            "As-tu déjà menti sur ton parcours ?",
            "Quel gros mensonge as-tu maintenu longtemps ?",
            "Mens-tu à tes amis régulièrement ?",
            "As-tu une fausse identité en ligne ?",
            "Sur quoi exagères-tu toujours ?",
            "Quel mensonge blanc dis-tu tout le temps ?",
            "As-tu menti sur tes diplômes ?",
            "Mens-tu sur ta vie amoureuse ?",
            "As-tu inventé des histoires sur toi ?",
            "Quel aspect de ta vie est une façade ?",
            "Sur quoi mens-tu pour impressionner ?",

            // Jalousie et envie
            "De qui es-tu le plus jaloux ?",
            "Quelle vie voudrais-tu voler ?",
            "Qui envies-tu secrètement ?",
            "Es-tu jaloux de tes amis ?",
            "Quelle réussite d'autrui te rend amer ?",
            "De quelle célébrité es-tu jaloux ?",
            "Envies-tu la vie de quelqu'un ici ?",
            "Quelle possession d'autrui veux-tu ?",
            "Es-tu jaloux en amour ?",
            "Qui a la vie que tu voudrais ?",
            "De quoi es-tu envieux chez les autres ?",
            "Quelle qualité voudrais-tu voler ?",
            "Es-tu jaloux des réseaux sociaux des autres ?",
            "De quelle relation es-tu jaloux ?",
            "Qui réussit mieux que toi et ça t'énerve ?",

            // Conflits
            "Avec qui es-tu en froid ?",
            "Qui détestes-tu vraiment ?",
            "Raconte ta pire dispute",
            "As-tu des ennemis ?",
            "Qui ne supportes-tu pas dans cette pièce ?",
            "As-tu déjà frappé quelqu'un ?",
            "Raconte une fois où tu as vraiment explosé",
            "Qui t'a le plus blessé ?",
            "As-tu déjà ruiné une amitié volontairement ?",
            "Avec qui ne parleras-tu plus jamais ?",
            "Quelle rancune gardes-tu ?",
            "Qui voudrais-tu confronter ?",
            "As-tu déjà cherché la bagarre ?",
            "Raconte ta vengeance la plus méchante",
            "Qui mériterait que tu lui dises ses 4 vérités ?",

            // Moments de solitude
            "Que fais-tu vraiment quand tu es seul ?",
            "As-tu des rituels en solo bizarres ?",
            "Que regardes-tu seul que personne ne sait ?",
            "Quelle est ton activité solitaire honteuse ?",
            "Parles-tu à toi-même ?",
            "Que fais-tu dans ta chambre que tu caches ?",
            "As-tu des hobbies secrets ?",
            "Comment passes-tu tes soirées seul vraiment ?",
            "Quelle est ta série/film plaisir coupable ?",
            "Que fais-tu sur Internet que tu caches ?",
            "As-tu des comportements bizarres en solo ?",
            "Quelle musique écoutes-tu seul honteusement ?",
            "Danses-tu seul dans ta chambre ?",
            "Que fais-tu pour te réconforter seul ?",
            "As-tu des conversations imaginaires ?",

            // Échecs
            "Quel est ton plus gros échec ?",
            "Quelle opportunité as-tu ratée ?",
            "Raconte une fois où tu as complètement foiré",
            "Quel examen/entretien as-tu raté lamentablement ?",
            "As-tu déjà été viré ?",
            "Quelle relation as-tu sabotée ?",
            "Quel projet as-tu abandonné honteusement ?",
            "Raconte ton fail le plus cuisant",
            "Quelle personne as-tu déçue le plus ?",
            "Quel talent as-tu gâché ?",
            "Quelle promesse n'as-tu jamais tenue ?",
            "Quel rêve as-tu tué toi-même ?",
            "Raconte comment tu as raté une grande chance",
            "Quel échec te hante encore ?",
            "Quelle erreur a changé ta vie négativement ?",

            // Opinions secrètes
            "Quelle opinion impopulaire as-tu ?",
            "Que penses-tu vraiment des gens ici ?",
            "Quelle croyance as-tu que tu caches ?",
            "Sur quoi es-tu hypocrite ?",
            "Quelle opinion politique caches-tu ?",
            "Que penses-tu vraiment de ton meilleur ami ?",
            "Quelle célébrité détestes-tu que tout le monde aime ?",
            "Quelle tendance trouves-tu stupide ?",
            "Sur quel sujet mens-tu sur ton opinion ?",
            "Que trouves-tu surestimé ?",
            "Quelle cause populaire te laisse indifférent ?",
            "Sur quoi as-tu changé d'avis honteusement ?",
            "Quelle opinion as-tu peur d'exprimer ?",
            "Que détestes-tu que les autres adorent ?",
            "Quel jugement portes-tu secrètement ?",

            // Comportements toxiques
            "As-tu déjà été toxique en relation ?",
            "Es-tu manipulateur parfois ?",
            "As-tu des red flags ?",
            "Es-tu possessif/jaloux excessivement ?",
            "As-tu déjà gaslighté quelqu'un ?",
            "Quel comportement toxique as-tu ?",
            "Es-tu un bon ami vraiment ?",
            "As-tu tendance à mentir en relation ?",
            "Es-tu égoïste dans tes relations ?",
            "As-tu déjà ghosté quelqu'un cruellement ?",
            "Profites-tu des gens ?",
            "Es-tu une mauvaise influence ?",
            "As-tu des comportements narcissiques ?",
            "Es-tu mesquin parfois ?",
            "Quel trait toxique devrais-tu changer ?",

            // Regrets amoureux
            "Qui regrettes-tu d'avoir laissé partir ?",
            "Quelle rupture regrettes-tu ?",
            "As-tu encore des sentiments pour un ex ?",
            "Qui était 'celui/celle qui s'est échappé' ?",
            "Raconte une histoire d'amour ratée",
            "As-tu déjà recontacté un ex ?",
            "Qui voudrais-tu récupérer ?",
            "Quelle occasion amoureuse as-tu ratée ?",
            "Y a-t-il quelqu'un que tu ne peux pas oublier ?",
            "As-tu pleuré pour quelqu'un récemment ?",
            "Qui t'a brisé le cœur le plus ?",
            "Penses-tu encore à un amour du passé ?",
            "As-tu des 'et si' en amour ?",
            "Regrettes-tu d'avoir quitté quelqu'un ?",
            "Y a-t-il un ex que tu stalkes encore ?",

            // Fantasmes et désirs
            "Quel est ton fantasme le plus fou ?",
            "Avec qui voudrais-tu coucher ici ?",
            "Quelle célébrité dans ton lit ?",
            "Quel est ton kink secret ?",
            "As-tu des désirs inavouables ?",
            "Quelle expérience sexuelle veux-tu essayer ?",
            "Qui trouves-tu sexy bizarrement ?",
            "Quel fantasme de groupe as-tu ?",
            "As-tu des pensées interdites ?",
            "Quel scénario t'excite le plus ?",
            "As-tu des fétiches que tu caches ?",
            "Quelle situation te fait fantasmer ?",
            "Qui est dans tes pensées intimes ?",
            "Quel rôle aimerais-tu jouer au lit ?",
            "Quelle pratique veux-tu explorer ?",

            // Vérités sur l'instant présent
            "Que penses-tu vraiment de cette soirée ?",
            "Qui t'énerve ici maintenant ?",
            "Préférerais-tu être ailleurs ?",
            "Qui ne voudrais-tu pas voir ici ?",
            "T'amuses-tu vraiment ?",
            "Qui trouves-tu attirant ici ?",
            "Que voudrais-tu faire maintenant ?",
            "Avec qui aimerais-tu partir d'ici ?",
            "Qui joue un rôle ici ?",
            "Quelle personne ici te met mal à l'aise ?",
            "Es-tu bourré maintenant ?",
            "Regrettes-tu d'être venu ?",
            "Qui voudrais-tu éviter ici ?",
            "Que préférerais-tu faire maintenant ?",
            "Avec qui voudrais-tu être seul ?",

            // Comportement en ligne
            "As-tu déjà troll quelqu'un en ligne ?",
            "Quelle est ta pire interaction sur les réseaux ?",
            "As-tu déjà harcelé quelqu'un en ligne ?",
            "Quel commentaire méchant regrettes-tu ?",
            "As-tu des comptes anonymes pour être méchant ?",
            "As-tu déjà envoyé des messages haineux ?",
            "Quelle est ta pire période sur les réseaux ?",
            "As-tu déjà été bloqué pour ton comportement ?",
            "Stalkes-tu des gens en ligne ?",
            "As-tu créé des dramas en ligne ?",
            "Quelle est ta pire action sur Internet ?",
            "As-tu déjà doxxé quelqu'un ?",
            "Participes-tu à des cancel cultures ?",
            "As-tu des regrets sur tes posts ?",
            "Quelle est ta persona en ligne vs réelle ?",

            // Sexualité
            "Quel âge avais-tu pour ta première fois ?",
            "Combien de partenaires sexuels as-tu eu ?",
            "As-tu déjà fait l'amour dans un lieu public ?",
            "Quelle est ton expérience la plus bizarre ?",
            "As-tu déjà eu un plan à trois ?",
            "Quel est ton pire coup au lit ?",
            "As-tu déjà simulé un orgasme ?",
            "Quelle est ta pire performance sexuelle ?",
            "As-tu des pratiques sexuelles inhabituelles ?",
            "Raconte ton expérience sexuelle la plus gênante",
            "As-tu déjà trompé quelqu'un ?",
            "Quelle est la chose la plus risquée que tu aies faite ?",
            "As-tu déjà envoyé des nudes ?",
            "Quelle partie de ton corps aimes-tu le moins montrer ?",
            "As-tu déjà fait quelque chose que tu regrettes au lit ?",

            // Vérités hardcore
            "Quel crime as-tu commis et caché ?",
            "As-tu déjà menti sous serment ?",
            "Quelle loi as-tu enfreinte récemment ?",
            "As-tu fait quelque chose d'illégal cette année ?",
            "Quel secret pourrait te détruire s'il sortait ?",
            "As-tu déjà fait du mal volontairement ?",
            "Quelle est la pire chose que tu aies faite ?",
            "As-tu des cadavres dans le placard ?",
            "Quel acte regrettes-tu profondément ?",
            "As-tu déjà ruiné la vie de quelqu'un ?",
            "Quelle vérité ne diras-tu jamais ?",
            "As-tu déjà pensé à faire du mal ?",
            "Quel secret emporteras-tu dans ta tombe ?",
            "As-tu fait des choses dont tu as honte profondément ?",
            "Quelle est ta part la plus sombre que personne ne connaît ?",

            // Divers
            "Ronfles-tu ?",
            "As-tu déjà fait pipi sous la douche ?",
            "Portes-tu toujours des sous-vêtements ?",
            "As-tu déjà pris un Uber/taxi sans payer ?",
            "Quelle est la chose la plus longue que tu aies volée ?",
            "As-tu déjà menti à un médecin ?",
            "Crois-tu en Dieu vraiment ?",
            "As-tu déjà fait semblant d'être malade pour le travail/école ?",
            "Quel âge mens-tu avoir ?",
            "As-tu déjà envoyé un texto à la mauvaise personne volontairement ?",
            "Quelle célébrité as-tu rencontrée et embarrassée ?",
            "As-tu déjà été arrêté par la police ?",
            "Quel est ton souvenir le plus bizarre ?",
            "As-tu déjà fait quelque chose juste pour les likes ?",
            "Quelle est la rumeur vraie sur toi ?",
            "As-tu déjà uriné en public ?",
            "Quelle est ta superstition la plus bizarre ?",
            "As-tu déjà cru à quelque chose de stupide ?",
            "Quel est ton talent le plus inutile ?",
            "As-tu un doudou que tu gardes encore ?",
            "Pleures-tu devant des films ?",
            "As-tu peur de quelque chose de ridicule ?",
            "Quelle est ta position pour dormir ?",
            "Dors-tu nu ?",
            "As-tu déjà parlé en dormant et dit quoi ?",
            "Quelle est ta pire allergie/intolérance ?",
            "As-tu des cicatrices embarrassantes ?",
            "Quel surnom détestes-tu ?",
            "As-tu déjà gagné quelque chose de stupide ?"
        ],

        dares: [
            // Défis physiques
            "Fais 10 pompes ou bois 3 gorgées",
            "Fais 20 jumping jacks ou distribue 4 gorgées",
            "Fais le poirier contre un mur ou cul sec",
            "Fais la planche 30 secondes ou bois 3 gorgées",
            "Fais 15 squats ou distribue 5 gorgées",
            "Fais le tour de la pièce à quatre pattes ou bois 2 gorgées",
            "Fais 10 burpees ou cul sec",
            "Tiens en équilibre sur un pied 1 minute ou bois 3 gorgées",
            "Fais la roue ou distribue 6 gorgées",
            "Fais 20 abdos ou bois 4 gorgées",
            "Fais le moonwalk à travers la pièce ou bois 2 gorgées",
            "Fais des pompes en applaudissant ou distribue 5 gorgées",
            "Fais le grand écart ou cul sec",
            "Fais 30 secondes de gainage ou bois 3 gorgées",
            "Fais 10 pompes d'une main ou distribue 8 gorgées",
            "Cours sur place 1 minute ou bois 2 gorgées",
            "Saute à la corde imaginaire 50 fois ou distribue 4 gorgées",
            "Fais le breakdance ou bois 3 gorgées",
            "Fais 5 tractions ou cul sec",
            "Marche en crabe dans la pièce ou bois 2 gorgées",

            // Défis technologiques
            "Appelle ton ex ou cul sec",
            "Poste un selfie moche sur Instagram ou distribue 5 gorgées",
            "Envoie un message bizarre à un contact aléatoire ou bois 4 gorgées",
            "Montre les 5 dernières photos de ta galerie ou bois 4 gorgées",
            "Envoie un vocal de 30s à ton crush ou distribue 6 gorgées",
            "Like les 10 derniers posts de ton ex ou bois 5 gorgées",
            "Poste une story embarrassante ou cul sec",
            "Appelle tes parents et dis que tu es amoureux ou bois 4 gorgées",
            "Envoie 'Je t'aime' à un contact aléatoire ou distribue 5 gorgées",
            "Change ta photo de profil pour une photo moche ou bois 3 gorgées",
            "Lis tes derniers messages à voix haute ou distribue 4 gorgées",
            "Montre ton historique de recherche ou cul sec",
            "Appelle ton crush et avoue tes sentiments ou bois 6 gorgées",
            "Envoie un snap embarrassant à ton crush ou distribue 5 gorgées",
            "Supprime ton appli préférée ou bois 4 gorgées",
            "Laisse quelqu'un poster à ta place sur les réseaux ou cul sec",
            "Montre tes DMs à tout le monde ou bois 5 gorgées",
            "Envoie un message vocal en chantant ou distribue 3 gorgées",
            "Like tous les posts de quelqu'un que tu détestes ou bois 4 gorgées",
            "Change ton statut en 'Célibataire et désespéré' ou distribue 5 gorgées",

            // Défis sociaux
            "Embrasse la personne à ta gauche ou bois 2 gorgées",
            "Fais un compliment bizarre à chaque personne ou bois 3 gorgées",
            "Fais un câlin de 30 secondes à quelqu'un ou distribue 2 gorgées",
            "Fais un lap dance à la personne de ton choix ou bois 6 gorgées",
            "Assieds-toi sur les genoux de quelqu'un 3 tours ou bois 4 gorgées",
            "Masse les épaules de 3 personnes ou distribue 5 gorgées",
            "Embrasse la main de tout le monde ou bois 3 gorgées",
            "Fais un slow avec la personne de ton choix ou distribue 4 gorgées",
            "Chuchote un secret à l'oreille de chacun ou cul sec",
            "Fais une déclaration d'amour à quelqu'un ou bois 5 gorgées",
            "Choisis quelqu'un et regarde-le dans les yeux 1 minute ou bois 3 gorgées",
            "Donne un surnom à chacun pour le reste de la soirée ou distribue 4 gorgées",
            "Fais un battle de regard avec quelqu'un ou bois 2 gorgées",
            "Complimente physiquement tout le monde ou distribue 5 gorgées",
            "Fais un bisou sur la joue à tout le monde ou bois 3 gorgées",
            "Choisis ton binôme pour la soirée ou distribue 4 gorgées",
            "Fais un câlin de groupe ou tout le monde boit 2 gorgées",
            "Raconte une histoire gênante sur la personne à ta droite ou bois 3 gorgées",
            "Mime l'orgasme devant tout le monde ou cul sec",
            "Serre la main à tout le monde de façon bizarre ou bois 2 gorgées",

            // Défis de danse
            "Danse sur une table pendant 30 secondes ou cul sec",
            "Fais un battle de danse avec quelqu'un ou buvez 3 gorgées chacun",
            "Fais semblant d'être un mannequin sur un podium ou bois 4 gorgées",
            "Danse le twerk pendant 20 secondes ou distribue 5 gorgées",
            "Fais une chorégraphie improvisée ou bois 3 gorgées",
            "Danse collé-serré avec quelqu'un ou distribue 4 gorgées",
            "Fais la danse de la pluie ou bois 2 gorgées",
            "Imite un clip de Beyoncé ou distribue 5 gorgées",
            "Fais le robot pendant 1 minute ou bois 3 gorgées",
            "Danse en touchant le sol ou cul sec",
            "Fais une danse sensuelle ou bois 4 gorgées",
            "Apprends un pas de danse à tout le monde ou distribue 5 gorgées",
            "Danse sans musique pendant 1 minute ou bois 3 gorgées",
            "Fais le moonwalk en dansant ou distribue 4 gorgées",
            "Improvise un ballet ou bois 2 gorgées",
            "Danse du ventre ou distribue 5 gorgées",
            "Fais une danse country ou bois 3 gorgées",
            "Imite un danseur de K-pop ou cul sec",
            "Fais le limbo imaginaire ou bois 2 gorgées",
            "Danse avec un objet ou distribue 3 gorgées",

            // Défis créatifs
            "Invente une histoire sur la personne à ta droite ou bois 2 gorgées",
            "Raconte une blague, si personne ne rit tu bois 3 gorgées",
            "Imite quelqu'un dans la pièce jusqu'à ce qu'on devine ou cul sec",
            "Imite un animal jusqu'à ce que quelqu'un devine ou bois 2 gorgées",
            "Raconte une blague en gardant un visage sérieux ou distribue 3 gorgées",
            "Imite un YouTubeur célèbre ou bois 2 gorgées",
            "Fais un one-man-show de 2 minutes ou distribue 5 gorgées",
            "Rappe sur un sujet donné par le groupe ou bois 4 gorgées",
            "Invente une chanson sur quelqu'un ici ou cul sec",
            "Fais un poème sur la soirée ou bois 3 gorgées",
            "Imite une célébrité pendant 5 minutes ou distribue 4 gorgées",
            "Raconte une histoire horrifique improvisée ou bois 2 gorgées",
            "Fais un sketch comique ou distribue 5 gorgées",
            "Invente un conte de fées bizarre ou bois 3 gorgées",
            "Fais le bruit de 5 animaux différents ou distribue 2 gorgées",
            "Crée un cocktail avec 3 ingrédients et bois-le ou distribue 6 gorgées",
            "Dessine quelqu'un avec les yeux fermés ou bois 2 gorgées",
            "Invente une langue et parle-la 2 minutes ou distribue 4 gorgées",
            "Fais un beatbox ou bois 3 gorgées",
            "Chante l'annuaire téléphonique ou cul sec",

            // Défis de chant
            "Chante l'alphabet à l'envers ou cul sec",
            "Chante une chanson sans musique ou bois 3 gorgées",
            "Fais un karaoké sur la prochaine chanson ou distribue 4 gorgées",
            "Chante en opéra ou bois 2 gorgées",
            "Rappe le générique d'un dessin animé ou distribue 3 gorgées",
            "Chante une berceuse à quelqu'un ou bois 2 gorgées",
            "Imite une diva en chantant ou distribue 4 gorgées",
            "Chante sous la douche imaginaire ou bois 3 gorgées",
            "Fais un duo avec quelqu'un ou buvez 2 gorgées chacun",
            "Chante en yaourt (fausses paroles) ou distribue 5 gorgées",
            "Chante la Marseillaise en métal ou cul sec",
            "Fais les choeurs pour la prochaine chanson ou bois 2 gorgées",
            "Chante une chanson d'amour à quelqu'un ou distribue 4 gorgées",
            "Imite un rappeur américain ou bois 3 gorgées",
            "Chante avec un accent étranger ou distribue 3 gorgées",
            "Beatbox pendant que quelqu'un rappe ou buvez 2 gorgées chacun",
            "Chante une chanson paillarde ou cul sec",
            "Fais un concert improvisé de 1 minute ou bois 4 gorgées",
            "Chante en fausset ou distribue 3 gorgées",
            "Improvise une chanson sur la personne à ta gauche ou bois 2 gorgées",

            // Défis alimentaires
            "Mange quelque chose du frigo les yeux fermés ou bois 3 gorgées",
            "Bois un mélange fait par le groupe ou cul sec",
            "Mange une cuillère de moutarde/sauce piquante ou distribue 5 gorgées",
            "Bois ton verre d'un coup ou distribue 4 gorgées",
            "Mange quelque chose sans les mains ou bois 2 gorgées",
            "Lèche un citron pendant 10 secondes ou distribue 3 gorgées",
            "Bois un verre à l'envers ou bois 2 gorgées supplémentaires",
            "Mange un aliment que tu détestes ou distribue 5 gorgées",
            "Bois avec une paille ridicule ou bois 2 gorgées",
            "Partage ta boisson avec quelqu'un ou buvez 3 gorgées chacun",
            "Mange un truc épicé ou distribue 4 gorgées",
            "Bois sans utiliser tes mains ou bois 3 gorgées",
            "Fais un shot de sauce soja/vinaigre ou cul sec",
            "Mange une combinaison bizarre choisie par le groupe ou distribue 6 gorgées",
            "Bois ton verre les yeux fermés ou bois 2 gorgées",
            "Partage un aliment bouche à bouche avec quelqu'un ou distribue 5 gorgées",
            "Mange comme un animal ou bois 2 gorgées",
            "Bois en faisant le poirier ou cul sec",
            "Lèche le sel sur la main de quelqu'un ou distribue 3 gorgées",
            "Mange 5 choses différentes en 30 secondes ou bois 4 gorgées",

            // Défis de transformation
            "Mets ton t-shirt à l'envers pour le reste de la partie ou distribue 4 gorgées",
            "Échange un vêtement avec quelqu'un ou cul sec",
            "Laisse quelqu'un te maquiller ou bois 5 gorgées",
            "Porte les vêtements de quelqu'un d'autre ou distribue 6 gorgées",
            "Laisse quelqu'un te coiffer bizarrement ou bois 4 gorgées",
            "Mets tes vêtements à l'envers ou distribue 3 gorgées",
            "Porte un accessoire ridicule toute la soirée ou bois 5 gorgées",
            "Laisse quelqu'un écrire sur ton visage ou cul sec",
            "Enlève un vêtement (au choix) ou distribue 8 gorgées",
            "Mets du rouge à lèvres exagéré ou bois 3 gorgées",
            "Porte les chaussures de quelqu'un d'autre ou distribue 2 gorgées",
            "Transforme-toi en momie avec du PQ ou bois 4 gorgées",
            "Fais-toi une coiffure ridicule ou distribue 3 gorgées",
            "Porte un déguisement improvisé ou bois 5 gorgées",
            "Échange ta tenue complète avec quelqu'un ou cul sec",
            "Mets des lunettes de soleil à l'envers ou bois 2 gorgées",
            "Laisse quelqu'un choisir ta tenue ou distribue 6 gorgées",
            "Porte un soutien-gorge par-dessus ton t-shirt ou bois 5 gorgées",
            "Fais-toi une fausse moustache ou distribue 2 gorgées",
            "Habille-toi comme le sexe opposé ou cul sec",

            // Défis de parole
            "Parle avec un accent pendant 3 tours ou distribue 4 gorgées",
            "Parle uniquement en rimes pendant 3 tours ou distribue 5 gorgées",
            "Parle comme un robot pendant 2 tours ou bois 3 gorgées",
            "Parle comme un pirate pendant 5 minutes ou bois 2 gorgées",
            "Ne parle plus jusqu'à ton prochain tour ou distribue 3 gorgées",
            "Parle en inversant les mots ou bois 4 gorgées",
            "Parle comme un bébé pendant 3 tours ou distribue 3 gorgées",
            "Parle uniquement en questions ou bois 2 gorgées",
            "Parle en verlan pendant 5 minutes ou distribue 4 gorgées",
            "Ne dis que des compliments jusqu'à ton tour ou bois 3 gorgées",
            "Parle comme un aristocrate ou distribue 2 gorgées",
            "Bégaye volontairement en parlant ou bois 2 gorgées",
            "Parle super vite pendant 2 tours ou distribue 3 gorgées",
            "Parle au ralenti ou bois 2 gorgées",
            "Ajoute 'meow' à la fin de chaque phrase ou distribue 4 gorgées",
            "Parle en alexandrins ou cul sec",
            "Répète tout ce que dit la personne à ta gauche ou bois 3 gorgées",
            "Parle comme un commentateur sportif ou distribue 3 gorgées",
            "Chuchote jusqu'à ton prochain tour ou bois 2 gorgées",
            "Crie au lieu de parler normalement ou distribue 4 gorgées",

            // Défis photo/vidéo
            "Prends une photo de groupe ridicule et poste-la ou bois 5 gorgées",
            "Fais une vidéo TikTok embarrassante ou cul sec",
            "Prends un selfie avec tout le monde ou distribue 3 gorgées",
            "Fais une story Instagram bizarre ou bois 4 gorgées",
            "Prends une photo en faisant la grimace ou distribue 2 gorgées",
            "Filme-toi en train de danser et poste ou bois 5 gorgées",
            "Fais un boomerang embarrassant ou distribue 3 gorgées",
            "Prends une photo compromettante avec quelqu'un ou buvez 3 gorgées chacun",
            "Fais un slow-motion ridicule ou bois 2 gorgées",
            "Prends 20 selfies d'affilée avec des grimaces ou distribue 4 gorgées",
            "Fais une vidéo de toi en train de chanter ou cul sec",
            "Crée un filtre Snapchat sur tout le monde ou bois 3 gorgées",
            "Fais une session photo de mannequin bizarre ou distribue 5 gorgées",
            "Filme ton meilleur move de danse ou bois 2 gorgées",
            "Fais un time-lapse de toi en train de boire ou distribue 3 gorgées",
            "Prends une photo artistique de ta boisson ou bois 2 gorgées",
            "Fais un panorama raté volontairement ou distribue 3 gorgées",
            "Filme-toi en faisant une grimace pendant 30s ou bois 4 gorgées",
            "Fais un collage photo ridicule et poste ou cul sec",
            "Prends une photo de pieds avec tout le monde ou distribue 2 gorgées",

            // Défis de vérité action combinés
            "Révèle ton dernier mensonge ou bois 4 gorgées",
            "Dis ce que tu penses vraiment de quelqu'un ici ou cul sec",
            "Avoue ton crush ou distribue 5 gorgées",
            "Raconte ton secret le plus gênant ou bois 6 gorgées",
            "Révèle ton historique de recherche ou distribue 8 gorgées",
            "Montre tes photos cachées ou cul sec",
            "Lis tes derniers messages à voix haute ou bois 5 gorgées",
            "Avoue ta plus grosse honte ou distribue 6 gorgées",
            "Dis qui tu trouves sexy ici ou bois 4 gorgées",
            "Révèle ton fantasme ou cul sec",
            "Raconte ton pire date en détails ou bois 5 gorgées",
            "Avoue quelque chose que personne ne sait ou distribue 7 gorgées",
            "Dis la vérité sur ta dernière cuite ou bois 4 gorgées",
            "Révèle ton vice secret ou distribue 5 gorgées",
            "Dis ce que tu penses de chacun honnêtement ou cul sec",

            // Défis extrêmes
            "Fais le tour du pâté de maisons en courant ou cul sec + distribue 10 gorgées",
            "Appelle ton crush et déclare-toi ou bois 8 gorgées",
            "Embrasse 3 personnes ou distribue 10 gorgées",
            "Déshabille-toi jusqu'aux sous-vêtements ou cul sec + 5 gorgées",
            "Fais un strip-tease ou bois 10 gorgées",
            "Lèche le pied de quelqu'un ou cul sec + distribue 8 gorgées",
            "Mange quelque chose tombé par terre ou distribue 6 gorgées",
            "Laisse quelqu'un te donner une fessée ou bois 5 gorgées",
            "Fais 50 pompes ou cul sec + 4 gorgées",
            "Reste en sous-vêtements 10 minutes ou distribue 10 gorgées",
            "Embrasse la personne la moins attirante pour toi ou cul sec",
            "Fais un body shot sur quelqu'un ou buvez 6 gorgées chacun",
            "Laisse quelqu'un te lécher le visage ou bois 7 gorgées",
            "Fais semblant d'avoir un orgasme bruyamment ou distribue 8 gorgées",
            "Lèche le sol ou cul sec + 10 gorgées",

            // Défis de couple/binôme
            "Choisis un partenaire et faites un slow ou buvez 4 gorgées chacun",
            "Fais un bisou esquimau avec quelqu'un ou distribue 3 gorgées",
            "Assieds-toi sur les genoux de quelqu'un tout le tour ou bois 3 gorgées",
            "Fais une battle de pouces avec quelqu'un, le perdant boit 3 gorgées",
            "Joue à pierre-feuille-ciseaux, le perdant boit 2 gorgées",
            "Fais un bras de fer, le perdant boit 4 gorgées",
            "Regarde quelqu'un dans les yeux 1 minute sans rire ou buvez 2 gorgées chacun",
            "Fais un concours de grimaces avec quelqu'un ou bois 2 gorgées",
            "Tiens la main de quelqu'un jusqu'à ton prochain tour ou bois 3 gorgées",
            "Partage ton verre avec quelqu'un ou buvez 2 gorgées chacun",
            "Fais un câlin de 1 minute avec quelqu'un ou distribue 3 gorgées",
            "Chuchote un secret à quelqu'un ou bois 4 gorgées",
            "Fais un compliment physique à quelqu'un ou distribue 2 gorgées",
            "Masse quelqu'un pendant 2 minutes ou bois 3 gorgées",
            "Échange de place avec quelqu'un pour 3 tours ou buvez 2 gorgées chacun",

            // Défis de groupe
            "Tout le monde doit t'imiter pendant 2 minutes ou tu bois 5 gorgées",
            "Organise un concours, le dernier boit 4 gorgées",
            "Fais deviner un mot en mime, si échec tu bois 3 gorgées",
            "Lance un défi au groupe, si tu perds tu bois 5 gorgées",
            "Tout le monde vote qui est le plus sexy, le gagnant distribue 5 gorgées",
            "Fais un battle, celui qui rit en premier boit 3 gorgées",
            "Organise une course, le dernier boit 4 gorgées",
            "Fais un sondage, la minorité boit 2 gorgées",
            "Lance un jeu de groupe improvisé ou bois 4 gorgées",
            "Tout le monde doit danser avec toi ou ils boivent 2 gorgées",
            "Fais voter qui doit boire ou tu distribues 6 gorgées",
            "Organise une pyramide humaine ou tout le monde boit 3 gorgées",
            "Fais un concours de qui reste sérieux, les rieurs boivent 2 gorgées",
            "Tout le monde t'imite ou ils boivent 3 gorgées",
            "Lance une vague dans le groupe ou tu bois 2 gorgées",

            // Défis intellectuels
            "Récite l'alphabet à l'envers en 30s ou bois 4 gorgées",
            "Compte à rebours de 100 à 0 par 7 ou bois 5 gorgées",
            "Épelle ton prénom à l'envers ou distribue 2 gorgées",
            "Récite 10 capitales ou bois 3 gorgées",
            "Nomme 20 pays en 1 minute ou distribue 5 gorgées",
            "Résous une énigme posée par le groupe ou bois 4 gorgées",
            "Conjugue un verbe à tous les temps ou cul sec",
            "Récite un poème ou bois 3 gorgées",
            "Fais une phrase avec tous les prénoms présents ou distribue 4 gorgées",
            "Compte en binaire jusqu'à 20 ou bois 5 gorgées",
            "Nomme tous les présidents français ou cul sec",
            "Récite la table de 7 ou bois 2 gorgées",
            "Épelle un mot compliqué choisi par le groupe ou distribue 3 gorgées",
            "Récite les paroles d'une chanson ou bois 3 gorgées",
            "Nomme 10 films d'un acteur ou distribue 4 gorgées",

            // Défis bizarres
            "Fais une déclaration d'amour à un objet ou bois 2 gorgées",
            "Parle à un objet pendant 2 minutes ou distribue 3 gorgées",
            "Fais semblant d'être une statue 3 minutes ou bois 4 gorgées",
            "Agis comme un chat pendant 5 minutes ou distribue 3 gorgées",
            "Fais le zombie ou bois 2 gorgées",
            "Imite une machine à laver ou distribue 3 gorgées",
            "Fais semblant d'être invisible ou bois 2 gorgées",
            "Agis comme si tu étais sous l'eau ou distribue 4 gorgées",
            "Fais le ventriloque ou bois 3 gorgées",
            "Imite un robot en panne ou distribue 2 gorgées",
            "Fais semblant d'être une plante ou bois 3 gorgées",
            "Agis comme un extraterrestre ou distribue 4 gorgées",
            "Fais le mime emprisonné ou bois 2 gorgées",
            "Imite quelqu'un qui a froid/chaud ou distribue 2 gorgées",
            "Fais semblant d'être un bébé ou bois 3 gorgées",
            "Agis comme un super-héros ou distribue 3 gorgées",
            "Fais le fantôme ou bois 2 gorgées",
            "Imite une voiture ou distribue 3 gorgées",
            "Fais semblant d'être vieux ou bois 2 gorgées",
            "Agis comme si tu étais ivre (plus qu'actuellement) ou distribue 4 gorgées",

            // Défis de temps
            "Reste silencieux 5 minutes ou bois 3 gorgées",
            "Ferme les yeux pendant 3 tours ou distribue 4 gorgées",
            "Reste debout sur une jambe tout le tour ou bois 2 gorgées",
            "Ne cligne pas des yeux 2 minutes ou distribue 3 gorgées",
            "Retiens ta respiration 1 minute ou bois 4 gorgées",
            "Reste immobile comme une statue 5 minutes ou distribue 5 gorgées",
            "Souris sans arrêt pendant 3 tours ou bois 2 gorgées",
            "Garde les bras levés 2 minutes ou distribue 3 gorgées",
            "Reste accroupi pendant 3 tours ou bois 4 gorgées",
            "Fais la planche 1 minute ou cul sec",
            "Tiens en équilibre sur les fesses 2 minutes ou distribue 3 gorgées",
            "Reste les yeux croisés 3 minutes ou bois 2 gorgées",
            "Ne souris pas pendant 5 tours ou distribue 4 gorgées",
            "Garde ta langue sortie 2 minutes ou bois 2 gorgées",
            "Reste sans bouger pendant qu'on te chatouille ou cul sec",

            // Défis dégradants (soft)
            "Lèche ton coude ou bois 2 gorgées",
            "Renifle les aisselles de quelqu'un ou distribue 4 gorgées",
            "Lèche ton assiette ou bois 3 gorgées",
            "Sens les pieds de quelqu'un ou cul sec",
            "Laisse quelqu'un te cracher dans la bouche ou distribue 10 gorgées",
            "Mange avec les pieds ou bois 5 gorgées",
            "Lèche le genou de quelqu'un ou distribue 3 gorgées",
            "Renifle les chaussettes de quelqu'un ou bois 4 gorgées",
            "Laisse quelqu'un te mettre de la salive sur le visage ou cul sec",
            "Bois dans la chaussure de quelqu'un ou distribue 8 gorgées",
            "Lèche la main de quelqu'un ou bois 3 gorgées",
            "Sens les chaussures de tout le monde ou distribue 5 gorgées",
            "Laisse quelqu'un te cracher dessus ou cul sec + 5 gorgées",
            "Lèche le doigt de pied de quelqu'un ou distribue 10 gorgées",
            "Bois la salive de quelqu'un ou cul sec + 8 gorgées"
        ]
    },

    gage: {
        name: "Gage de Con",
        // Continué dans le prochain fichier pour ne pas dépasser la limite...
    },

    // Nouvelles catégories ajoutées
    mime: {
        name: "Mime & Charades",
        challenges: [
            // Mimes d'animaux
            "Mime un chat qui se fait caresser",
            "Mime un chien qui veut sortir",
            "Mime un pingouin qui glisse",
            "Mime une girafe qui boit",
            "Mime un singe qui mange une banane",
            "Mime un serpent qui rampe",
            "Mime un kangourou qui saute",
            "Mime un oiseau qui construit son nid",
            "Mime un éléphant qui se douche",
            "Mime un poisson qui nage",

            // Mimes d'actions quotidiennes
            "Mime quelqu'un qui se brosse les dents bourré",
            "Mime quelqu'un qui essaie de marcher avec des talons",
            "Mime quelqu'un qui reçoit un texto de son ex",
            "Mime quelqu'un qui voit son crush",
            "Mime quelqu'un qui essaie de rester éveillé",
            "Mime quelqu'un qui a oublié son mot de passe",
            "Mime quelqu'un qui essaie de paraître sobre",
            "Mime quelqu'un qui prend un selfie parfait",
            "Mime quelqu'un qui danse seul dans sa chambre",
            "Mime quelqu'un qui reçoit de mauvaises nouvelles",

            // Mimes de métiers
            "Mime un coiffeur en action",
            "Mime un serveur maladroit",
            "Mime un DJ en plein set",
            "Mime un prof ennuyeux",
            "Mime un médecin qui examine",
            "Mime un policier qui poursuit",
            "Mime un pompier qui sauve",
            "Mime un chef cuisinier stressé",
            "Mime un artiste qui peint",
            "Mime un danseur de ballet",

            // Mimes de célébrités
            "Mime une diva qui fait un caprice",
            "Mime un rappeur en concert",
            "Mime un mannequin sur un podium",
            "Mime une star qui signe des autographes",
            "Mime un influenceur qui fait une vidéo",
            "Mime un chanteur d'opéra",
            "Mime un acteur qui reçoit un Oscar",
            "Mime une rock star qui détruit sa guitare",
            "Mime un sportif qui célèbre",
            "Mime un magicien qui rate son tour",

            // Mimes de situations embarrassantes
            "Mime quelqu'un qui pète en public",
            "Mime quelqu'un qui glisse sur une peau de banane",
            "Mime quelqu'un dont le pantalon craque",
            "Mime quelqu'un qui se fait surprendre",
            "Mime quelqu'un qui trébuche et fait semblant de rien",
            "Mime quelqu'un qui a oublié qu'il est en visio",
            "Mime quelqu'un qui envoie un message à la mauvaise personne",
            "Mime quelqu'un qui se fait larguer",
            "Mime quelqu'un qui vomit discrètement",
            "Mime quelqu'un qui essaie de fuir une conversation",

            // Charades combinées
            "Mime un film d'horreur célèbre (le groupe devine)",
            "Mime une chanson connue (le groupe devine)",
            "Mime un dessin animé (le groupe devine)",
            "Mime une série TV populaire (le groupe devine)",
            "Mime un jeu vidéo (le groupe devine)",
            "Mime une marque connue (le groupe devine)",
            "Mime un pays (le groupe devine)",
            "Mime une célébrité française (le groupe devine)",
            "Mime un sport (le groupe devine)",
            "Mime une application smartphone (le groupe devine)"
        ]
    },

    hotSeat: {
        name: "Hot Seat",
        challenges: [
            // Le siège éjectable - 5 questions rapides
            "Le groupe pose 5 questions rapides - tu dois répondre en moins de 5 secondes chacune",
            "Réponds OUI ou NON seulement : Le groupe te pose 10 questions pièges",
            "Jeu du NI OUI NI NON : Le groupe t'interroge pendant 1 minute, tu ne dois dire ni oui ni non",
            "Avoue 3 secrets en 30 secondes ou bois 6 gorgées",
            "Le groupe vote : Quelle est ta qualité ? Ta pire défaut ? Pourquoi tu es là ?",

            // Questions embarrassantes en rafale
            "Nomme 5 personnes que tu as embrassées ou bois 5 gorgées",
            "Cite 3 mensonges que tu as dits cette semaine ou distribue 6 gorgées",
            "Avoue 3 choses que tu caches à tes parents",
            "Nomme toutes les personnes que tu trouves sexy ici ou bois 5 gorgées",
            "Révèle 3 de tes recherches Google les plus bizarres",

            // Hot seat - tout le monde participe
            "Chaque personne te pose une question embarrassante - tu dois répondre à toutes",
            "Tour de table : tout le monde dit ce qu'il pense vraiment de toi",
            "Chacun devine un secret sur toi - avoue si c'est vrai",
            "Le groupe vote pour ton pire défaut - tu dois l'assumer et expliquer",
            "Tout le monde te donne un conseil - tu expliques pourquoi tu ne le suis pas",

            // Défis rapides en série
            "Fais 3 imitations de personnes ici en 30 secondes",
            "Dis un compliment et un défaut à chaque personne en 1 minute",
            "Raconte 3 histoires embarrassantes en 2 minutes",
            "Avoue à qui tu as pensé en dernier de façon romantique",
            "Explique tes 3 plus gros regrets en 1 minute",

            // Vérités intenses
            "Classe les personnes ici du plus au moins attirant - explique pourquoi",
            "Si tu devais embrasser 3 personnes ici, qui et pourquoi ?",
            "Révèle ce que tu penses vraiment de chacun - sois honnête",
            "Avoue tes 3 plus gros mensonges de la soirée",
            "Dis qui tu éviterais dans cette pièce et pourquoi",

            // Hot seat interactif
            "Le groupe te donne 3 défis - tu dois en choisir un et le faire",
            "Tout le monde écrit une question secrète - tu pioches et réponds",
            "Le groupe décide : action ou vérité ? Tu n'as pas le choix",
            "Chacun te donne un gage - tu dois tous les faire en 2 minutes",
            "Le groupe vote pour ton secret le plus dark - tu dois le révéler"
        ]
    },

    duel: {
        name: "Duel",
        challenges: [
            // Duels physiques
            "Bras de fer - le perdant boit 4 gorgées",
            "Concours de pompes - le premier à 20 gagne, l'autre boit 5 gorgées",
            "Concours de squats - le premier à abandonner boit 4 gorgées",
            "Battle de danse - le groupe vote, le perdant boit 3 gorgées",
            "Concours de gainage - le premier qui lâche boit 5 gorgées",
            "Battle de moonwalk - le pire boit 2 gorgées",
            "Concours de flexibilité - qui fait le meilleur grand écart ? Le perdant boit 4 gorgées",
            "Pierre-feuille-ciseaux en 5 manches - le perdant boit 6 gorgées",
            "Course à cloche-pied - le dernier boit 3 gorgées",
            "Concours d'équilibre sur une jambe - le premier qui pose le pied boit 3 gorgées",

            // Duels de talent
            "Battle de rap - le groupe vote, le perdant boit 4 gorgées",
            "Concours de beatbox - le pire boit 3 gorgées",
            "Battle de chant - le groupe juge, le perdant boit 4 gorgées",
            "Concours d'imitations - le moins drôle boit 3 gorgées",
            "Battle de blagues - le moins drôle boit 5 gorgées",
            "Concours de grimaces - le groupe vote, le perdant boit 2 gorgées",
            "Battle de freestyle - le pire boit 4 gorgées",
            "Concours de stands up - le moins drôle boit 6 gorgées",
            "Battle de beatbox - le perdant distribue 4 gorgées",
            "Concours de mime - le groupe décide, le perdant boit 3 gorgées",

            // Duels intellectuels
            "Quiz culture G - 10 questions, le perdant boit 5 gorgées",
            "Concours de calcul mental - le plus lent boit 3 gorgées",
            "Battle d'orthographe - le premier qui se trompe boit 4 gorgées",
            "Concours de capitales - le premier à 10 gagne, l'autre boit 5 gorgées",
            "Battle de répliques de films - le premier qui sèche boit 3 gorgées",
            "Concours de conjugaison - le perdant boit 4 gorgées",
            "Réciter l'alphabet à l'envers - le plus lent boit 3 gorgées",
            "Compter à rebours de 100 par 7 - le premier qui se trompe boit 5 gorgées",
            "Battle de paroles de chansons - le premier qui bloque boit 4 gorgées",
            "Concours de noms de pays - le premier à 20 gagne, l'autre boit 5 gorgées",

            // Duels de regard et résistance
            "Battle de regard - le premier qui rit boit 3 gorgées",
            "Concours de sérieux - le premier qui sourit boit 2 gorgées",
            "Battle de chatouilles - le premier qui rit boit 4 gorgées",
            "Concours 'Ni oui ni non' - le premier qui dit oui/non boit 5 gorgées",
            "Battle de statues - le premier qui bouge boit 3 gorgées",

            // Duels alcoolisés
            "Concours de cul sec - le plus lent boit 3 gorgées supplémentaires",
            "Battle de shots - le premier à 3 gagne, l'autre distribue 6 gorgées",
            "Concours de résistance - buvez en même temps, le premier qui s'arrête perd",
            "Russian Beer Pong improvisé - le perdant boit tout",
            "Concours de vitesse - videz vos verres, le plus lent boit encore 4 gorgées",

            // Duels créatifs
            "Inventer une histoire - le groupe vote la meilleure, le perdant boit 3 gorgées",
            "Battle de dessin les yeux fermés - le pire boit 3 gorgées",
            "Concours de poésie improvisée - le moins romantique boit 4 gorgées",
            "Battle de compliments - le premier à court d'idées boit 3 gorgées",
            "Concours de tchatche - draguez la même personne, elle choisit le gagnant, le perdant boit 5 gorgées",

            // Duels de chance
            "Pile ou face en 5 manches - le perdant boit 5 gorgées",
            "Dés : Le plus petit score boit la différence en gorgées",
            "Tirage au sort - le perdant fait un gage choisi par le gagnant",
            "Roulette de bouteille - elle désigne le perdant qui boit 4 gorgées",
            "Le groupe choisit secrètement le gagnant - le perdant boit 6 gorgées"
        ]
    },

    vote: {
        name: "Vote",
        challenges: [
            // Votes sur les qualités
            "Qui est le/la plus drôle ? - Cette personne distribue 5 gorgées",
            "Qui est le/la plus sexy ? - Les autres boivent 2 gorgées",
            "Qui est le/la plus intelligent(e) ? - Cette personne choisit qui boit 4 gorgées",
            "Qui est le/la plus fou/folle ? - Cette personne fait un défi de son choix ou boit 3 gorgées",
            "Qui est le/la plus timide ? - Cette personne doit faire un truc fou ou boire 4 gorgées",

            // Votes sur les défauts
            "Qui est le/la plus bourré(e) ? - Cette personne boit 4 gorgées",
            "Qui est le/la plus bavard(e) ? - Cette personne reste silencieuse 2 tours ou boit 3 gorgées",
            "Qui est le/la plus menteur/menteuse ? - Cette personne avoue un mensonge ou boit 5 gorgées",
            "Qui est le/la plus égoïste ? - Cette personne offre 1 shot à quelqu'un ou boit 4 gorgées",
            "Qui est le/la plus jaloux/jalouse ? - Cette personne avoue de qui ou boit 3 gorgées",

            // Votes sur les comportements
            "Qui a le plus de chances de finir la nuit en boîte de nuit ? - Boit 2 gorgées",
            "Qui a le plus de chances de vomir ce soir ? - Boit 3 gorgées",
            "Qui a le plus de chances de se réveiller dans un endroit bizarre ? - Boit 3 gorgées",
            "Qui a le plus de chances d'envoyer un texto à son ex ce soir ? - Boit 4 gorgées et donne son téléphone",
            "Qui a le plus de chances de faire quelque chose de stupide ce soir ? - Boit 3 gorgées",

            // Votes relationnels
            "Qui ferait le meilleur couple ici ? - Ils boivent 3 gorgées ensemble",
            "Qui se déteste secrètement ? - Ils doivent s'expliquer ou boire 5 gorgées chacun",
            "Qui a déjà eu un crush sur quelqu'un ici ? - Le groupe devine, si c'est vrai tu bois 5 gorgées",
            "Qui embrasse le mieux selon vous ? - Cette personne choisit quelqu'un à embrasser ou distribue 6 gorgées",
            "Qui est le plus friend-zoned ? - Cette personne avoue par qui ou boit 4 gorgées",

            // Votes sur le passé
            "Qui a la pire histoire de rupture ? - Raconte-la ou bois 5 gorgées",
            "Qui a fait la pire connerie d'ado ? - Raconte ou bois 4 gorgées",
            "Qui a le passé le plus dark ? - Révèle quelque chose ou bois 6 gorgées",
            "Qui a le pire casier judiciaire (même imaginaire) ? - Avoue ou bois 4 gorgées",
            "Qui a eu le premier date le plus nul ? - Raconte ou bois 3 gorgées",

            // Votes extrêmes
            "Qui survivrait le moins longtemps dans la nature ? - Boit 3 gorgées",
            "Qui deviendrait fou en premier dans une apocalypse zombie ? - Boit 4 gorgées",
            "Qui serait le premier à trahir le groupe ? - Doit se justifier ou boire 5 gorgées",
            "Qui a le plus de secrets inavouables ? - Révèle-en un ou bois 6 gorgées",
            "Qui finirait en prison en premier ? - Explique pourquoi ou bois 4 gorgées",

            // Votes physiques
            "Qui a le plus beau sourire ? - Distribue 3 gorgées",
            "Qui a les plus beaux yeux ? - Choisit qui boit 4 gorgées",
            "Qui est le/la mieux habillé(e) ? - Les autres boivent 2 gorgées",
            "Qui a le meilleur style ? - Distribue 4 gorgées",
            "Qui a le rire le plus contagieux ? - Fait rire quelqu'un ou boit 3 gorgées",

            // Votes de groupe
            "Vote : Qui devrait boire ? - La personne avec le plus de votes boit 5 gorgées",
            "Vote : Qui mérite un gage ? - Le groupe décide du gage",
            "Vote : Qui doit embrasser quelqu'un ? - Le groupe choisit qui",
            "Vote : Qui est le MVP de la soirée ? - Distribue 10 gorgées comme il veut",
            "Vote : Qui devrait partir en premier ? - Cette personne distribue 5 gorgées",

            // Votes secrets
            "Vote secret : Qui est le plus hypocrite ? - Révélation, cette personne boit 4 gorgées",
            "Vote secret : Qui vous énerve le plus ? - Révélation, justification ou 5 gorgées",
            "Vote secret : Qui voudriez-vous embrasser ? - Révélation publique",
            "Vote secret : De qui êtes-vous jaloux ? - Le groupe devine, révélation finale",
            "Vote secret : Qui ne devrait pas être là ? - Révélation, explications nécessaires"
        ]
    },

    histoire: {
        name: "Histoire à Raconter",
        challenges: [
            // Histoires personnelles
            "Raconte ton pire date en détails - si tu fais rire, distribue 5 gorgées, sinon bois 3",
            "Raconte ta pire cuite - le groupe vote si c'est vrai, sinon bois 4 gorgées",
            "Raconte comment tu as rencontré ton ex - le plus cringe distribue 3 gorgées",
            "Raconte ton moment le plus embarrassant à l'école",
            "Raconte une fois où tu t'es fait attraper en flagrant délit",
            "Raconte ta pire soirée de ta vie",
            "Raconte ton premier baiser en détails",
            "Raconte une fois où tu as menti et tu t'es fait griller",
            "Raconte ton fail le plus épique en public",
            "Raconte une histoire où tu as eu très honte",

            // Histoires inventées
            "Invente une histoire d'horreur - si tu fais peur, distribue 4 gorgées",
            "Invente une histoire romantique sur 2 personnes ici - elles boivent 3 gorgées",
            "Invente un complot impliquant tout le monde ici",
            "Raconte l'avenir dans 10 ans de la personne à ta gauche",
            "Invente une légende urbaine sur cette soirée",
            "Crée une histoire de super-héros avec les gens présents",
            "Invente une série Netflix sur le groupe",
            "Raconte le scénario d'un film d'horreur avec vous tous",
            "Invente l'origine secrète de quelqu'un ici",
            "Crée une prophétie sur la fin de soirée",

            // Histoires collaboratives
            "Commence une histoire - chacun ajoute une phrase - la plus drôle gagne et distribue 5 gorgées",
            "Histoire à continuer : Commence par 'Il était une fois...' - le suivant continue",
            "Histoire dont tu es le héros : le groupe décide de tes actions",
            "Raconte une histoire, le groupe l'interrompt avec 'Et puis?' jusqu'à ce que tu bloques",
            "Histoire collective : chacun dit un mot - doit faire sens - le premier qui bloque boit",

            // Histoires vraies ou fausses
            "Raconte 3 histoires : 2 vraies, 1 fausse - le groupe devine",
            "Raconte quelque chose de fou - le groupe vote si c'est vrai - les perdants boivent",
            "2 vérités 1 mensonge sur ton ex - le groupe devine",
            "Raconte ton histoire la plus incroyable - si personne n'y croit tu bois 5 gorgées",
            "Histoire vraie ou fake ? Le groupe parie des gorgées",

            // Histoires de groupe
            "Raconte une histoire sur quelqu'un ici (vraie) - cette personne confirme ou tu bois 4 gorgées",
            "Raconte un souvenir collectif - les autres complètent",
            "Décris comment tu imagines la vie secrète de chacun",
            "Raconte la pire chose que vous ayez faite ensemble",
            "Histoire de cette soirée vue du futur - imagine dans 10 ans",

            // Histoires thématiques
            "Raconte une histoire de fantôme que tu connais",
            "Histoire la plus chelou de ta famille",
            "Raconte une légende de ton pays/région",
            "Histoire la plus bizarre que tu aies vécue en voyage",
            "Raconte un rêve bizarre que tu as fait",
            "Histoire paranormale que tu as vécue ou qu'on t'a racontée",
            "Raconte ton histoire de soirée alcoolisée la plus folle",
            "Histoire d'un mensonge qui est allé trop loin",
            "Raconte comment tu as gâché quelque chose d'important",
            "Histoire de la fois où tu as failli te faire choper",

            // Histoires interactives
            "Raconte une histoire en mimant - si le groupe devine tu distribues 6 gorgées",
            "Raconte une histoire avec des accents différents pour chaque personnage",
            "Histoire contée en chantant - si tu arrives au bout distribue 5 gorgées",
            "Raconte une histoire triste - le premier qui pleure distribue 3 gorgées",
            "Histoire à suspense - le groupe doit deviner la fin",

            // Confessions
            "Raconte un secret que tu n'as jamais dit à personne",
            "Histoire de ta plus grosse trahison",
            "Raconte quelque chose dont tu as honte depuis longtemps",
            "Histoire de ton plus gros regret en détails",
            "Raconte comment tu as fait du mal à quelqu'un involontairement"
        ]
    },

    regles: {
        name: "Nouvelles Règles",
        challenges: [
            // Règles de parole
            "Nouvelle règle : Interdiction de dire 'je' pendant 3 tours - sinon 2 gorgées",
            "Nouvelle règle : Parlez uniquement en questions - sinon 2 gorgées",
            "Nouvelle règle : Interdiction de pointer du doigt - sinon 3 gorgées",
            "Nouvelle règle : Interdiction de dire les prénoms - sinon 2 gorgées",
            "Nouvelle règle : Ajoutez 'dans ton cul' à la fin de chaque phrase - sinon 2 gorgées",
            "Nouvelle règle : Interdiction de rire - le premier qui rit boit 3 gorgées",
            "Nouvelle règle : Parlez uniquement en rimes - sinon 3 gorgées",
            "Nouvelle règle : Interdiction de dire 'oui' ou 'non' - sinon 2 gorgées",
            "Nouvelle règle : Appelez-vous par des surnoms uniquement - sinon 2 gorgées",
            "Nouvelle règle : Parlez comme des pirates - sinon 2 gorgées",

            // Règles gestuelles
            "Nouvelle règle : Touchez-vous le nez quand vous buvez - sinon 2 gorgées supplémentaires",
            "Nouvelle règle : Levez la main avant de parler - sinon 2 gorgées",
            "Nouvelle règle : Claquement de doigts avant et après chaque phrase - sinon 2 gorgées",
            "Nouvelle règle : Debout pour boire - sinon 3 gorgées",
            "Nouvelle règle : Trinquez avec tout le monde avant de boire - sinon 2 gorgées",
            "Nouvelle règle : Tenez votre verre de la main gauche uniquement - sinon 2 gorgées",
            "Nouvelle règle : Faites une révérence avant de boire - sinon 2 gorgées",
            "Nouvelle règle : Fermez les yeux quand vous buvez - sinon 2 gorgées",
            "Nouvelle règle : Applaudissez quand quelqu'un boit - sinon tout le monde boit 1 gorgée",
            "Nouvelle règle : Faites un tour sur vous-même avant de vous asseoir - sinon 2 gorgées",

            // Règles de maître
            "Nouvelle règle : Tu es le maître des gorgées - distribue comme tu veux pendant 3 tours",
            "Nouvelle règle : Tu deviens le roi/reine - tout le monde obéit pendant 3 tours",
            "Nouvelle règle : Tu choisis un vice-roi - vous distribuez ensemble 5 tours",
            "Nouvelle règle : Tu es le juge - tu décides qui boit et combien pendant 3 tours",
            "Nouvelle règle : Tu es le dictateur - impose 3 règles absurdes pendant 5 tours",

            // Règles de groupe
            "Nouvelle règle : Quand quelqu'un boit, tout le monde boit pendant 3 tours",
            "Nouvelle règle : Le dernier à toucher le sol boit 3 gorgées - dès que quelqu'un touche le sol",
            "Nouvelle règle : Si quelqu'un dit 'putain', tout le monde boit",
            "Nouvelle règle : Quand quelqu'un rit, le suivant doit rire aussi - sinon 2 gorgées",
            "Nouvelle règle : Interdiction de croiser les jambes - sinon 2 gorgées",

            // Règles de désignation
            "Nouvelle règle : Tu peux pointer quelqu'un du doigt - il boit 2 gorgées (utilisable 3 fois)",
            "Nouvelle règle : À chaque fois qu'on dit ton prénom, tu distribues 2 gorgées",
            "Nouvelle règle : Tu choisis un partenaire - vous buvez toujours ensemble",
            "Nouvelle règle : Tu as un bouclier - tu peux refiler 3 gorgées à quelqu'un d'autre (utilisable 3 fois)",
            "Nouvelle règle : Tu es immunisé pendant 3 tours - tu ne bois pas",

            // Règles absurdes
            "Nouvelle règle : Tout le monde doit danser en buvant - sinon 2 gorgées",
            "Nouvelle règle : Parlez en inversant les syllabes - sinon 3 gorgées",
            "Nouvelle règle : Chantez au lieu de parler - sinon 2 gorgées",
            "Nouvelle règle : Faites semblant d'être des poulets - sinon 3 gorgées",
            "Nouvelle règle : Riez diaboliquement après chaque phrase - sinon 2 gorgées",
            "Nouvelle règle : Parlez avec un accent étranger - sinon 2 gorgées",
            "Nouvelle règle : Bégayez volontairement - sinon 2 gorgées",
            "Nouvelle règle : Parlez super fort - sinon 2 gorgées",
            "Nouvelle règle : Chuchotez uniquement - sinon 3 gorgées",
            "Nouvelle règle : Imitez la personne avant vous - sinon 2 gorgées",

            // Règles de contact
            "Nouvelle règle : Interdiction de toucher son téléphone - sinon 4 gorgées",
            "Nouvelle règle : Interdiction de toucher son visage - sinon 2 gorgées",
            "Nouvelle règle : Tenez-vous la main avec votre voisin - sinon 3 gorgées chacun",
            "Nouvelle règle : Interdiction de toucher la table - sinon 2 gorgées",
            "Nouvelle règle : Gardez les bras croisés sauf pour boire - sinon 2 gorgées",

            // Règles de temps
            "Nouvelle règle : Vous avez 5 secondes pour répondre - sinon 3 gorgées",
            "Nouvelle règle : Pause de 30 secondes entre chaque gorgée - sinon 2 gorgées supplémentaires",
            "Nouvelle règle : Comptez à rebours de 10 avant de boire - sinon recommencez",
            "Nouvelle règle : Interdiction de boire pendant 2 tours (sauf obligation) - stockez vos gorgées",
            "Nouvelle règle : Double dose : toutes les gorgées comptent double pendant 3 tours"
        ]
    },

    compliment: {
        name: "Compliments",
        challenges: [
            // Compliments physiques
            "Fais un compliment physique à la personne la plus proche",
            "Dis ce que tu trouves de plus beau chez chacun",
            "Complimente les yeux de 3 personnes ici",
            "Dis à quelqu'un qu'il/elle a un beau sourire et pourquoi",
            "Complimente le style vestimentaire de tout le monde",

            // Compliments de personnalité
            "Dis à la personne à ta gauche ce que tu admires chez elle",
            "Complimente l'humour de quelqu'un et donne un exemple",
            "Dis à quelqu'un pourquoi tu es content(e) qu'il/elle soit là",
            "Fais un compliment sincère sur l'intelligence de quelqu'un",
            "Dis à quelqu'un quelle qualité tu voudrais lui voler",

            // Compliments créatifs
            "Compare quelqu'un à une célébrité (positivement) et explique pourquoi",
            "Dis à quelqu'un à quel super-héros il/elle te fait penser",
            "Fais un compliment en utilisant une métaphore poétique",
            "Dis à quelqu'un quelle chanson te fait penser à lui/elle (positivement)",
            "Compare chaque personne à un animal mignon et explique",

            // Compliments d'actions
            "Remercie quelqu'un pour quelque chose qu'il/elle a fait",
            "Dis à quelqu'un ce qu'il/elle fait de mieux",
            "Complimente la façon dont quelqu'un traite les autres",
            "Dis à quelqu'un pourquoi il/elle est un(e) bon(ne) ami(e)",
            "Remercie chaque personne pour quelque chose de spécifique",

            // Compliments de groupe
            "Fais un compliment à tout le groupe sur l'ambiance",
            "Dis ce que tu aimes le plus dans ce groupe d'amis",
            "Complimente l'énergie de la soirée grâce à quelqu'un",
            "Dis pourquoi tu es heureux/heureuse d'être ici avec eux",
            "Fais un compliment collectif sincère",

            // Compliments cachés
            "Révèle un compliment que tu pensais en secret sur quelqu'un",
            "Dis à quelqu'un ce que tu n'oses jamais lui dire de positif",
            "Avoue à qui tu as pensé du bien récemment et pourquoi",
            "Révèle ce que tu admires secrètement chez quelqu'un",
            "Dis un truc gentil que tu pensais mais jamais dit",

            // Compliments comparatifs
            "Dis en quoi quelqu'un ici t'inspire",
            "Explique ce que tu as appris de positif de quelqu'un",
            "Dis à quelqu'un en quoi il/elle te rend meilleur(e)",
            "Complimente quelqu'un sur ce qu'il/elle fait mieux que toi",
            "Dis à quelqu'un quelle qualité de lui/elle tu voudrais avoir",

            // Compliments de couple/amitié
            "Complimente la relation entre 2 personnes ici",
            "Dis quel duo ici tu trouves le plus mignon et pourquoi",
            "Complimente l'amitié de 2 personnes présentes",
            "Dis pourquoi 2 personnes ici vont bien ensemble",
            "Fais un compliment sur la complicité d'un binôme",

            // Compliments sur le changement
            "Dis à quelqu'un comment il/elle a positivement changé",
            "Complimente les progrès de quelqu'un",
            "Dis ce que tu trouves de mieux chez quelqu'un maintenant vs avant",
            "Complimente l'évolution positive de quelqu'un",
            "Dis à quelqu'un ce qu'il/elle a accompli dont tu es fier(e)",

            // Compliments profonds
            "Dis à quelqu'un pourquoi tu l'apprécie vraiment",
            "Fais un compliment sincère qui vient du cœur à quelqu'un",
            "Dis à quelqu'un ce qu'il/elle apporte de spécial au groupe",
            "Explique pourquoi tu es reconnaissant(e) d'avoir quelqu'un dans ta vie",
            "Dis à quelqu'un ce que tu n'oublieras jamais de lui/elle",

            // Compliments multiples
            "Fais 3 compliments différents à la même personne",
            "Complimente une qualité différente de chaque personne",
            "Dis un compliment physique et un compliment de personnalité à quelqu'un",
            "Fais un compliment passé, présent et futur à quelqu'un",
            "Donne 5 raisons pour lesquelles quelqu'un est génial"
        ]
    },

    cascade: {
        name: "Cascade",
        challenges: [
            // Cascades simples
            "Cascade : Tout le monde boit 3 gorgées en même temps",
            "Cascade : Chacun son tour boit - le dernier boit double",
            "Cascade : Buvez en chaîne - chacun après l'autre sans pause",
            "Cascade : Comptez de 1 à 20, chaque chiffre = quelqu'un boit",
            "Cascade : Tour de table - chacun boit le nombre de son âge en gorgées",

            // Cascades cumulatives
            "Cascade cumulative : Le 1er boit 1, le 2e boit 2, etc.",
            "Cascade inverse : Le dernier boit 1, l'avant-dernier 2, etc.",
            "Cascade double : Tout le monde boit, puis re-boit le double",
            "Cascade progressive : Ajoutez 1 gorgée à chaque personne",
            "Cascade multiplicative : Doublez à chaque personne (1, 2, 4, 8...)",

            // Cascades avec défis
            "Cascade + danse : Chacun danse puis boit",
            "Cascade + compliment : Complimentez votre voisin avant de boire",
            "Cascade + imitation : Imitez quelqu'un avant de boire",
            "Cascade + chant : Chantez une phrase puis buvez",
            "Cascade + vérité : Avouez quelque chose puis buvez",

            // Cascades de choix
            "Cascade démocratique : Chacun vote - la majorité boit",
            "Cascade de désignation : Chacun désigne qui boit après",
            "Cascade de sacrifice : Chacun peut boire double pour sauver quelqu'un",
            "Cascade de partage : Distribuez vos gorgées aux autres",
            "Cascade d'immunité : 1 personne est sauvée - les autres boivent double",

            // Cascades à thème
            "Cascade alphabétique : Dans l'ordre alphabétique des prénoms",
            "Cascade par âge : Du plus jeune au plus vieux",
            "Cascade par taille : Du plus grand au plus petit",
            "Cascade par ordre d'arrivée à la soirée",
            "Cascade selon les signes astro : Feu, Terre, Air, Eau",

            // Cascades compétitives
            "Cascade battle : Formez 2 équipes - l'équipe qui boit le plus vite gagne",
            "Cascade élimination : Le plus lent à chaque tour est éliminé",
            "Cascade survival : Buvez à tour de rôle - le dernier debout gagne",
            "Cascade duel : 2 camps - le camp perdant boit double",
            "Cascade relais : Course de relais avec des verres",

            // Cascades créatives
            "Cascade histoire : Racontez une histoire - à chaque mot clé tout le monde boit",
            "Cascade musique : À chaque beat de la musique tout le monde boit",
            "Cascade chorégraphie : Créez une chorégraphie de groupe en buvant",
            "Cascade chanson : Chantez une chanson - buvez aux refrains",
            "Cascade mime : Mimez en cascade - celui qui se trompe boit",

            // Cascades extrêmes
            "Méga cascade : Tout le monde cul sec en même temps",
            "Cascade infernale : Buvez, dansez, chantez, rebuvez",
            "Cascade sans fin : Continuez jusqu'à ce que quelqu'un abandonne",
            "Cascade pyramide : 1 boit, puis 2, puis 3, puis tout le monde",
            "Cascade finale : Double dose pour tout le monde",

            // Cascades interactives
            "Cascade compliment : Dites un compliment puis buvez ensemble",
            "Cascade bisou : Faites la bise à chacun puis buvez",
            "Cascade câlin : Câlin de groupe puis tout le monde boit",
            "Cascade high five : High five à tout le monde puis buvez",
            "Cascade toast : Portez un toast ensemble puis buvez",

            // Cascades selon conditions
            "Cascade conditionnelle : Si tu as déjà... bois",
            "Cascade sélective : Ceux qui portent du noir boivent",
            "Cascade zodiacale : Ton signe astrologique décide",
            "Cascade saisonnière : Selon ton mois de naissance",
            "Cascade numérique : Selon le chiffre de ton âge",

            // Cascades de règles
            "Cascade silence : Buvez en silence - le premier qui parle boit double",
            "Cascade yeux fermés : Tout le monde boit les yeux fermés",
            "Cascade debout : Tout le monde se lève et boit debout",
            "Cascade synchronisée : Buvez parfaitement en même temps",
            "Cascade rituelle : Créez un rituel de groupe avant de boire"
        ]
    },

    hotSexy: {
        name: "Hot & Sexy",
        challenges: [
            // Défis de séduction soft
            "Fais un regard séducteur à la personne de ton choix pendant 10 secondes",
            "Dis ta meilleure phrase de drague à quelqu'un ici",
            "Fais un clin d'œil sexy à 3 personnes différentes",
            "Mords-toi la lèvre en regardant quelqu'un dans les yeux",
            "Fais ton meilleur sourire charmeur à tout le monde",
            "Dis 3 compliments sexy à la personne à ta gauche",
            "Fais une danse sensuelle de 20 secondes",
            "Murmure quelque chose de coquin à l'oreille de quelqu'un",
            "Lèche tes lèvres de façon provocante en regardant quelqu'un",
            "Fais ton meilleur regard langoureux",

            // Défis de contact physique
            "Embrasse quelqu'un sur la joue très lentement",
            "Caresse le bras de quelqu'un sensuellement",
            "Masse la nuque de quelqu'un pendant 30 secondes",
            "Fais courir ton doigt sur le dos de quelqu'un",
            "Embrasse la main de quelqu'un comme dans un film romantique",
            "Enlace quelqu'un par derrière pendant 20 secondes",
            "Touche délicatement le visage de quelqu'un",
            "Frôle 'accidentellement' la personne à ta droite",
            "Pose ta tête sur l'épaule de quelqu'un pendant 1 minute",
            "Tiens la main de quelqu'un et caresse-la du pouce",

            // Défis de bisous
            "Embrasse quelqu'un sur la joue - mais très proche de la bouche",
            "Bisou esquimau avec la personne de ton choix",
            "Embrasse le cou de quelqu'un (si accord)",
            "Fais un bisou papillon avec tes cils sur la joue de quelqu'un",
            "Embrasse 3 parties du corps de quelqu'un (mains, front, joue...)",
            "Bisou dans le cou de la personne à ta gauche",
            "Embrasse l'épaule de quelqu'un",
            "Bisou soufflé à tout le monde de façon sexy",
            "Embrasse le lobe d'oreille de quelqu'un",
            "Donne un French kiss à la personne de ton choix ou bois 8 gorgées",

            // Vérités osées
            "Révèle ton fantasme le plus secret",
            "Dis avec qui tu coucherais ici (si tout était possible)",
            "Raconte ton expérience sexuelle la plus folle",
            "Avoue ton kink le plus bizarre",
            "Quelle partie du corps trouves-tu la plus sexy ?",
            "Raconte où est le lieu le plus risqué où tu l'as fait",
            "Quelle position préfères-tu et pourquoi ?",
            "Avoue combien de partenaires tu as eu",
            "Raconte ton pire plan cul",
            "Dis qui tu trouves le/la plus sexy dans cette pièce",

            // Défis de strip-tease soft
            "Enlève un accessoire de façon sexy",
            "Desserre un bouton/baisse une bretelle de façon sensuelle",
            "Fais un mini strip-tease de 15 secondes",
            "Enlève tes chaussures de la façon la plus sexy possible",
            "Défais tes cheveux lentement en regardant quelqu'un",
            "Montre ton épaule de façon provocante",
            "Remonte légèrement ton haut/bas en dansant",
            "Enlève ta veste/pull de façon sensuelle",
            "Dénoue quelque chose sur toi lentement",
            "Fais semblant d'enlever ton haut (sans vraiment le faire)",

            // Défis de lap dance
            "Fais un lap dance de 20 secondes à quelqu'un",
            "Assieds-toi sur les genoux de quelqu'un face à lui/elle pendant 30 secondes",
            "Danse de façon provocante devant quelqu'un",
            "Fais un slow très collé-serré avec quelqu'un",
            "Twerk devant la personne de ton choix",
            "Danse sensuellement contre quelqu'un",
            "Fais une danse du ventre pour quelqu'un",
            "Ondule du corps devant quelqu'un pendant 20 secondes",
            "Fais ton meilleur déhanché face à quelqu'un",
            "Danse en touchant sensuellement ton corps",

            // Body shots et défis alcool sexy
            "Fais un body shot sur quelqu'un (sel, shot, citron)",
            "Bois dans le nombril de quelqu'un (si accord)",
            "Lèche du sel sur le cou/poignet de quelqu'un",
            "Verse une goutte d'alcool sur toi et fais lécher à quelqu'un",
            "Partage ton verre en buvant bouche à bouche (presque)",
            "Fais-toi verser de l'alcool dans la bouche par quelqu'un",
            "Bois un shot pendant qu'on te fait un massage",
            "Body shot inversé : quelqu'un fait un shot sur toi",
            "Bois ton verre pendant qu'on te caresse les cheveux",
            "Shot challenge : bois pendant qu'on t'embrasse le cou",

            // Jeux de rôle sexy
            "Joue une scène de film romantique avec quelqu'un",
            "Fais semblant de séduire quelqu'un dans un bar",
            "Rejoue une scène de série hot (soft version)",
            "Incarne un(e) escort girl/boy qui drague un client",
            "Fais le/la prof séducteur/séductrice",
            "Joue le rôle d'un mannequin sexy en séance photo",
            "Fais comme si tu draguais quelqu'un sur Tinder IRL",
            "Incarne quelqu'un qui fait un strip-tease (habillé)",
            "Joue un rendez-vous speed dating très chaud",
            "Fais une audition pour un film pour adultes (soft)",

            // Défis de groupe sexy
            "Le groupe vote : qui devrait t'embrasser ?",
            "Choisis 2 personnes et fais-leur un massage d'épaules simultané",
            "Tout le monde te touche en même temps (épaules, bras, cheveux...)",
            "Le groupe décide quelle partie de ton corps est la plus sexy",
            "Fais un compliment sexy à chaque personne",
            "3 personnes te font un câlin de groupe sensuel",
            "Tout le monde te dit ce qu'il trouve sexy chez toi",
            "Le groupe choisit ton meilleur atout physique",
            "Fais une pyramide sensuelle avec 3 personnes",
            "Câlin de groupe : tu es au centre, les autres t'enlacent",

            // Défis de lit/chambre
            "Décris ta routine avant de coucher avec quelqu'un",
            "Raconte où tu aimes qu'on te touche",
            "Mime comment tu te comportes au lit (soft version)",
            "Avoue quel son tu fais pendant l'acte",
            "Raconte ta technique de séduction préférée",
            "Mime un orgasme de façon exagérée",
            "Dis ce que tu aimes qu'on te fasse",
            "Raconte une position que tu veux essayer",
            "Avoue si tu préfères donner ou recevoir",
            "Décris ton partenaire sexuel idéal",

            // Défis de vêtements
            "Échange un vêtement avec quelqu'un du sexe opposé",
            "Porte le soutien-gorge de quelqu'un par-dessus ton t-shirt",
            "Mets un vêtement sexy qui ne t'appartient pas",
            "Défais ton pantalon/jupe de 2 boutons",
            "Porte les sous-vêtements de quelqu'un sur la tête",
            "Enlève tes chaussettes de la façon la plus sexy",
            "Mets ton t-shirt à l'envers et mouillé (spray d'eau)",
            "Porte uniquement une veste sans rien dessous (fermée)",
            "Transforme un vêtement en tenue sexy",
            "Reste en débardeur/marcel pour le reste de la partie",

            // Défis couples/binômes sexy
            "Choisis un partenaire et regardez-vous dans les yeux 2 minutes sans rire",
            "Slow ultra collé avec quelqu'un pendant une chanson entière",
            "Allongez-vous l'un sur l'autre (décemment) pendant 30s",
            "Fais des bisous papillon partout sur le visage de quelqu'un",
            "Câlin ultra serré pendant 1 minute avec quelqu'un",
            "Masse sensuellement les mains de quelqu'un",
            "Chuchote des choses coquines à l'oreille de quelqu'un pendant 30s",
            "Caresse le visage de quelqu'un très lentement",
            "Joue avec les cheveux de quelqu'un sensuellement",
            "Respire dans le cou de quelqu'un pendant 20 secondes",

            // Défis extrêmes (18+)
            "7 minutes au paradis avec la personne de ton choix ou bois 10 gorgées",
            "Embrasse passionnément quelqu'un ou cul sec",
            "Strip-tease complet jusqu'aux sous-vêtements ou distribue 15 gorgées",
            "Lèche du chocolat/chantilly sur la peau de quelqu'un",
            "Laisse quelqu'un te donner un suçon",
            "Embrasse 3 personnes sur la bouche ou bois 12 gorgées",
            "Fais un lap dance complet ou cul sec + 5 gorgées",
            "Montre ton soutien-gorge/boxer ou distribue 10 gorgées",
            "Mordille le cou de quelqu'un ou bois 8 gorgées",
            "Session massage sensuel 2 minutes sur quelqu'un"
        ]
    }
};
